onboarding = false

[theme]
name = "gruvbox"
auto_switch = false

[ui]
prompt_new_tab_name = false
status_indicators = "dots"
window_title = "herdr: {workspace}"

[worktrees]
directory = "~/Code/worktrees"
