## Exports
export PS1="\u@\h:\w$ "
export EDITOR=vim


## Functions

# Open SSH sessions in new tmux window and connect to a nested tmux session.
function tmux_ssh () {
  if [ -n "$2" ]; then
    ssh "$@"
  else
    tmux new-window -n "$1" """ssh -t "$1" 'tmux attach'"""
  fi
}
alias ssh="tmux_ssh"

# Change to directory of the frontmost Finder window.
function cdf () {
  cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
}

# Find the target of a redirecting URL.
function expandurl () {
# wget -S $1 2>&1 | grep ^Location;
  curl -sIL $1 | grep '^Location' | tail -n 1 | awk '{print $2}'
}

# Change git remote by supplying user/repo.
function gitremote () {
  if [ -d ".git" ] && [ -n "$1" ]; then
    git remote rm origin
    git remote add origin git@github.com:${1}.git
    git config master.remote origin
    git config master.merge refs/heads/master
    echo "Updated git remote to git@github.com:${1}.git"
  else
    echo "Not a git repository."
  fi
}
