" Environment
scriptencoding utf-8
set background=dark
set colorcolumn=81
set encoding=utf-8
set fileencoding=utf-8
set hidden
set hlsearch
set ignorecase
set list
set listchars=tab:┄\ ,trail:·
set number
set pastetoggle=<leader>v
set relativenumber
set shiftwidth=2
set showcmd
set smartcase
set splitbelow
set splitright
set tabstop=2
set visualbell

" Leader
nmap <space> <leader>

" Plugins
call plug#begin()

Plug 'ajh17/VimCompletesMe'

Plug 'alvan/vim-closetag'
let g:closetag_filenames='*.html,*.jsx,*.xml'
let g:closetag_xhtml_filenames='*.jsx,*.xml'

Plug 'airblade/vim-rooter'

Plug 'ap/vim-buftabline'
let g:buftabline_indicators=1
let g:buftabline_show=1

Plug 'editorconfig/editorconfig-vim'

Plug 'itchyny/lightline.vim'
let g:lightline={
	\ 'active': {
	\   'left': [ [ 'mode', 'paste' ],
	\             [ 'gitbranch' ],
	\             [ 'filename' ] ],
	\   'right': [ [ 'lineinfo' ],
	\              [],
	\              [ 'filetype' ] ]
	\ },
	\ 'colorscheme': 'gruvbox',
	\ 'component_function': {
	\   'gitbranch': 'fugitive#head'
	\ },
	\ }

Plug 'jiangmiao/auto-pairs'
Plug 'jparise/vim-graphql'

Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
let $FZF_DEFAULT_COMMAND='ag -g ""'
let $FZF_DEFAULT_OPTS="--exact"
command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, {'options': '--delimiter : --nth 4..'}, <bang>0)
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>c :Commands<cr>
nnoremap <leader>h :History<cr>
nnoremap <leader>p :Files<cr>
nnoremap <leader>s :call fzf#run({'source': prosession#ListSessions(), 'sink': 'Prosession', 'down': '30%'})<cr>
nnoremap <leader>t :call fzf#vim#tags(expand('<cword>'))<cr>
nnoremap <leader>T :Tags<cr>
nnoremap <leader>/ :call fzf#vim#ag(expand('<cword>'))<cr>
nnoremap <leader>? :Ag<cr>

Plug 'junegunn/vim-peekaboo'
Plug 'justinmk/vim-dirvish'

Plug 'mbbill/undotree'
nnoremap <leader>u :UndotreeToggle<cr>:UndotreeFocus<cr>

Plug 'mhinz/vim-sayonara'
nnoremap <silent> <leader>q :Sayonara<cr>
nnoremap <silent> <leader>x :Sayonara!<cr>
let g:sayonara_confirm_quit=1

Plug 'mhinz/vim-signify'
let g:signify_vcs_list=['git']

Plug 'morhetz/gruvbox'
let g:gruvbox_contrast_dark="hard"
let g:gruvbox_sign_column="bg0"

Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'

Plug 'tpope/vim-commentary'

Plug 'tpope/vim-fugitive'
nnoremap <leader>d :Gvdiff<cr>

Plug 'tpope/vim-obsession'
Plug 'dhruvasagar/vim-prosession' " Must be loaded after vim-obsession
Plug 'tpope/vim-sensible'

Plug 'unblevable/quick-scope'
let g:qs_highlight_on_keys=['f', 'F', 't', 'T']

Plug 'w0rp/ale'
let g:ale_linters={
	\   'css':        ['stylelint'],
	\   'dockerfile': ['hadolint'],
	\   'javascript': ['eslint'],
	\   'php':        ['phpcs'],
	\   'sh':         ['shellcheck'],
	\ }
let g:ale_php_phpcs_standard='WordPress'
let g:ale_sign_column_always=1
let g:ale_sign_error='✖'
let g:ale_sign_warning='⚠'

call plug#end()

" Buffers
nnoremap <leader><tab> :b#<cr>
nnoremap <leader><right> :bnext<cr>
nnoremap <leader><left> :bprev<cr>
nnoremap <leader>z :u<cr>
nnoremap <leader>Z :redo<cr>
nnoremap S :w<cr>

" Colorscheme
if &t_Co >= 256
	colorscheme gruvbox
end

" Harder
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" Jumps
nnoremap <tab> <c-o>
nnoremap <s-tab> <c-i>

" Mouse
if has('mouse')
  set mouse=a
end

" Navigation
inoremap jj <esc>

" Windows
map <space><space> <c-w>
