tab_bar_align        start
tab_bar_background   #0d1011
tab_bar_edge         left
tab_bar_margin_color #0d1011
tab_bar_min_tabs     1
tab_bar_style        hidden
tab_separator        ""
tab_title_max_length 50
tab_title_template   " {index}  {title} {f'[{num_windows}]' if num_windows > 1 else ''}"

active_tab_background   #0d1011
active_tab_font_style   normal
active_tab_foreground   #a89984
inactive_tab_background #0d1011
inactive_tab_font_style normal
inactive_tab_foreground #7c6f64
