wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: []
    rows: []
  refreshInterval: 1
  mods:
    feedreader:
      enabled: true
      feeds:
        - https://lobby.vip.wordpress.com/feed/
      feedLimit: 10
      position:
        top: 2
        left: 1
        width: 1
        height: 1
      updateInterval: 3600
    gcal:
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "czarate@qz.com"
      enabled: true
      eventCount: 12
      multiCalendar: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 300
      secretFile: "~/.config/wtf/gcal-credentials.json"
      showDeclined: true
      timezone: "America/New_York"
      withLocation: true
    github:
      # apiKey: "Supply WTF_GITHUB_TOKEN env var"
      customQueries:
        othersPRs:
          title: "Others Pull Requests"
          filter: "is:open is:pr -author:chriszarate"
      enabled: true
      enableStatus: true
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 300
      repositories:
        qz-react: "Quartz"
      username: "chriszarate"
    jira:
      # apiKey: "Supply WTF_JIRA_API_KEY env var"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://quartz.atlassian.net"
      email: "czarate@qz.com"
      enabled: true
      jql: "assignee = currentuser() AND status != closed"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      project: "QZ2019"
      refreshInterval: 900
      verifyServerCertificate: true
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    prettyweather:
      enabled: true
      city: "New York"
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 300
      unit: "u"
      view: 0
      language: "en"
    trello:
      # accessToken: "Supply WTF_TRELLO_ACCESS_TOKEN env var"
      # apiKey: "Supply WTF_TRELLO_APP_KEY env var"
      board: "Tasks"
      enabled: true
      list: "To Do"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
      username: chriszarate
