export EDITOR="vim"
export PAGER="less"
export PATH="/opt/homebrew/opt/rustup/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.bin:$HOME/.orbstack/bin"
export PROMPT='%~ > '
if [ -S "$HOME/.ssh/autoproxxy-ssh-agent.socket" ]; then
	export SSH_AUTH_SOCK="$HOME/.ssh/autoproxxy-ssh-agent.socket"
fi

# completions
if type brew &>/dev/null; then
	FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

	autoload -Uz compinit
	compinit
fi

# fnm (node.js version manager)
eval "$(fnm env --use-on-cd --log-level=quiet --version-file-strategy=recursive)"
