# Trimmed from https://github.com/mathiasbynens/dotfiles

# Add local paths
PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Remove duplicate entries, preserving order
export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=':' '!a[$1]++' | awk '{gsub(/:$/,""); print}')

# Source .bashrc
[ -r ~/.bashrc ] && source ~/.bashrc

# Source .bash_aliases
[ -r ~/.bash_aliases ] && source ~/.bash_aliases

# Source .local_exports (private or local-specific stuff)
[ -r ~/.local_exports ] && source ~/.local_exports

# Always open a tmux session.
if [[ "$TERM" != screen* ]]; then
  tmux attach
fi

# Connect to ssh-agent session (requires keychain).
eval `keychain --eval --quiet --agents ssh --nogui`

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh

# Add tab completion for git commands
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
. /usr/local/etc/bash_completion.d/git-completion.bash
fi
